// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using ClientServerCommon;

public static class KodConfig
{
	public static int GetPublisher()
	{
#if UNITY_EDITOR
		return _ProductPublisher.KodGames;
#else
		return KodGames.ExternalCall.KodConfigPlugin.GetPublisher();
#endif
	}

	// GetWay Server
	public static string GetServerIP()
	{
#if UNITY_EDITOR
		return ConfigDatabase.DefaultCfg.ClientConfig.serverIP;
#else
		return KodGames.ExternalCall.KodConfigPlugin.GetServerIP();
#endif
	}

	public static int GetServerPort()
	{
#if UNITY_EDITOR
		return ConfigDatabase.DefaultCfg.ClientConfig.serverPort;
#else
		return KodGames.ExternalCall.KodConfigPlugin.GetServerPort();
#endif
	}

	public static string GetAuthServerIP()
	{
		return ConfigDatabase.DefaultCfg.ClientConfig.authServerIP;
	}

	public static int GetAuthServerPort()
	{
		return ConfigDatabase.DefaultCfg.ClientConfig.authServerPort;
	}
}