//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/SLGV1.proto
namespace proto.SLGV1
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaseData")]
  public partial class BaseData : global::ProtoBuf.IExtensible
  {
    public BaseData() {}
    

    private int _code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_StartGame")]
  public partial class RQ_StartGame : global::ProtoBuf.IExtensible
  {
    public RQ_StartGame() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_StartGame")]
  public partial class RS_StartGame : global::ProtoBuf.IExtensible
  {
    public RS_StartGame() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }

    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_RoleLogin")]
  public partial class RQ_RoleLogin : global::ProtoBuf.IExtensible
  {
    public RQ_RoleLogin() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_RoleLogin")]
  public partial class RS_RoleLogin : global::ProtoBuf.IExtensible
  {
    public RS_RoleLogin() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }

    private CharacterInfo _userInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CharacterInfo userInfo
    {
      get { return _userInfo; }
      set { _userInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<RoomInfo> _allRoom = new global::System.Collections.Generic.List<RoomInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"allRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RoomInfo> allRoom
    {
      get { return _allRoom; }
    }
  
    private readonly global::System.Collections.Generic.List<ResidentInfo> _allResident = new global::System.Collections.Generic.List<ResidentInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"allResident", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResidentInfo> allResident
    {
      get { return _allResident; }
    }
  
    private readonly global::System.Collections.Generic.List<ProduceRoom> _allProRoom = new global::System.Collections.Generic.List<ProduceRoom>();
    [global::ProtoBuf.ProtoMember(5, Name=@"allProRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProduceRoom> allProRoom
    {
      get { return _allProRoom; }
    }
  
    private readonly global::System.Collections.Generic.List<StoreRoom> _allStoreRoom = new global::System.Collections.Generic.List<StoreRoom>();
    [global::ProtoBuf.ProtoMember(6, Name=@"allStoreRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<StoreRoom> allStoreRoom
    {
      get { return _allStoreRoom; }
    }
  
    private readonly global::System.Collections.Generic.List<ResidentRoom> _allResidentRoom = new global::System.Collections.Generic.List<ResidentRoom>();
    [global::ProtoBuf.ProtoMember(7, Name=@"allResidentRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResidentRoom> allResidentRoom
    {
      get { return _allResidentRoom; }
    }
  
    private readonly global::System.Collections.Generic.List<ProduceEquipInfo> _proEquip = new global::System.Collections.Generic.List<ProduceEquipInfo>();
    [global::ProtoBuf.ProtoMember(8, Name=@"proEquip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProduceEquipInfo> proEquip
    {
      get { return _proEquip; }
    }
  

    private AllMagicSkillInfo _allMagicSkill = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"allMagicSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllMagicSkillInfo allMagicSkill
    {
      get { return _allMagicSkill; }
      set { _allMagicSkill = value; }
    }

    private Box _boxs = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"boxs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Box boxs
    {
      get { return _boxs; }
      set { _boxs = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterInfo")]
  public partial class CharacterInfo : global::ProtoBuf.IExtensible
  {
    public CharacterInfo() {}
    
    private int _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private string _roleName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }

    private string _headimgurl = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headimgurl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headimgurl
    {
      get { return _headimgurl; }
      set { _headimgurl = value; }
    }

    private int _feNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"feNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int feNum
    {
      get { return _feNum; }
      set { _feNum = value; }
    }

    private int _woodNum = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"woodNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int woodNum
    {
      get { return _woodNum; }
      set { _woodNum = value; }
    }

    private int _magicNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"magicNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int magicNum
    {
      get { return _magicNum; }
      set { _magicNum = value; }
    }

    private int _appNum = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"appNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int appNum
    {
      get { return _appNum; }
      set { _appNum = value; }
    }

    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }

    private int _lv = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }

    private int _power = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }

    private int _grailNum = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"grailNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int grailNum
    {
      get { return _grailNum; }
      set { _grailNum = value; }
    }

    private int _popNum = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"popNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int popNum
    {
      get { return _popNum; }
      set { _popNum = value; }
    }

    private int _builderNum = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"builderNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int builderNum
    {
      get { return _builderNum; }
      set { _builderNum = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _castleSkin = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(16, Name=@"castleSkin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> castleSkin
    {
      get { return _castleSkin; }
    }
  

    private int _loginDays = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"loginDays", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loginDays
    {
      get { return _loginDays; }
      set { _loginDays = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _thirdAcctInfo = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(18, Name=@"thirdAcctInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> thirdAcctInfo
    {
      get { return _thirdAcctInfo; }
    }
  

    private int _stageId = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_CreateRoleName")]
  public partial class RQ_CreateRoleName : global::ProtoBuf.IExtensible
  {
    public RQ_CreateRoleName() {}
    
    private string _roleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_CreateRoleName")]
  public partial class RS_CreateRoleName : global::ProtoBuf.IExtensible
  {
    public RS_CreateRoleName() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }

    private CharacterInfo _userInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CharacterInfo userInfo
    {
      get { return _userInfo; }
      set { _userInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _xFloorOriginOffset = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"xFloorOriginOffset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> xFloorOriginOffset
    {
      get { return _xFloorOriginOffset; }
    }
  

    private int _leftTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"leftTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int leftTime
    {
      get { return _leftTime; }
      set { _leftTime = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _residents = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"residents", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> residents
    {
      get { return _residents; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"A_RoomInfo")]
  public partial class A_RoomInfo : global::ProtoBuf.IExtensible
  {
    public A_RoomInfo() {}
    
    private A_RoomInfo _roomInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public A_RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_CheckCreateNewRoom")]
  public partial class RQ_CheckCreateNewRoom : global::ProtoBuf.IExtensible
  {
    public RQ_CheckCreateNewRoom() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_CheckCreateNewRoom")]
  public partial class RS_CheckCreateNewRoom : global::ProtoBuf.IExtensible
  {
    public RS_CheckCreateNewRoom() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private readonly global::System.Collections.Generic.List<ConsumeItem> _neeedItem = new global::System.Collections.Generic.List<ConsumeItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"neeedItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ConsumeItem> neeedItem
    {
      get { return _neeedItem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConsumeItem")]
  public partial class ConsumeItem : global::ProtoBuf.IExtensible
  {
    public ConsumeItem() {}
    
    private int _produceType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"produceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int produceType
    {
      get { return _produceType; }
      set { _produceType = value; }
    }
    private int _needNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"needNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int needNum
    {
      get { return _needNum; }
      set { _needNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_CreateNewRoom")]
  public partial class RQ_CreateNewRoom : global::ProtoBuf.IExtensible
  {
    public RQ_CreateNewRoom() {}
    
    private int _roomType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _xFloorOriginOffset = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"xFloorOriginOffset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> xFloorOriginOffset
    {
      get { return _xFloorOriginOffset; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_CreateNewRoom")]
  public partial class RS_CreateNewRoom : global::ProtoBuf.IExtensible
  {
    public RS_CreateNewRoom() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }

    private RoomInfo _baseRoomInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"baseRoomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RoomInfo baseRoomInfo
    {
      get { return _baseRoomInfo; }
      set { _baseRoomInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProduceRoom")]
  public partial class ProduceRoom : global::ProtoBuf.IExtensible
  {
    public ProduceRoom() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }

    private int _toBeCollected = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"toBeCollected", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int toBeCollected
    {
      get { return _toBeCollected; }
      set { _toBeCollected = value; }
    }

    private int _speedProd = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"speedProd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int speedProd
    {
      get { return _speedProd; }
      set { _speedProd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StoreRoom")]
  public partial class StoreRoom : global::ProtoBuf.IExtensible
  {
    public StoreRoom() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _depot;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"depot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int depot
    {
      get { return _depot; }
      set { _depot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"A_ProduceRoom")]
  public partial class A_ProduceRoom : global::ProtoBuf.IExtensible
  {
    public A_ProduceRoom() {}
    
    private readonly global::System.Collections.Generic.List<ProduceRoom> _proRoom = new global::System.Collections.Generic.List<ProduceRoom>();
    [global::ProtoBuf.ProtoMember(1, Name=@"proRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProduceRoom> proRoom
    {
      get { return _proRoom; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"A_StoreRoom")]
  public partial class A_StoreRoom : global::ProtoBuf.IExtensible
  {
    public A_StoreRoom() {}
    
    private readonly global::System.Collections.Generic.List<StoreRoom> _storeRoom = new global::System.Collections.Generic.List<StoreRoom>();
    [global::ProtoBuf.ProtoMember(1, Name=@"storeRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<StoreRoom> storeRoom
    {
      get { return _storeRoom; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResidentRoom")]
  public partial class ResidentRoom : global::ProtoBuf.IExtensible
  {
    public ResidentRoom() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _residentIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"residentIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> residentIds
    {
      get { return _residentIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _appointmentTimes = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"appointmentTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> appointmentTimes
    {
      get { return _appointmentTimes; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _state = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> state
    {
      get { return _state; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Q_CheckResidentRoomState")]
  public partial class Q_CheckResidentRoomState : global::ProtoBuf.IExtensible
  {
    public Q_CheckResidentRoomState() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"A_ResidentRoom")]
  public partial class A_ResidentRoom : global::ProtoBuf.IExtensible
  {
    public A_ResidentRoom() {}
    
    private readonly global::System.Collections.Generic.List<ResidentRoom> _residentRoom = new global::System.Collections.Generic.List<ResidentRoom>();
    [global::ProtoBuf.ProtoMember(1, Name=@"residentRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResidentRoom> residentRoom
    {
      get { return _residentRoom; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProduceEquipInfo")]
  public partial class ProduceEquipInfo : global::ProtoBuf.IExtensible
  {
    public ProduceEquipInfo() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _wHJHProducting = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"wHJHProducting", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> wHJHProducting
    {
      get { return _wHJHProducting; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Q_CheckProductEquipState")]
  public partial class Q_CheckProductEquipState : global::ProtoBuf.IExtensible
  {
    public Q_CheckProductEquipState() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"A_ProduceEquipInfo")]
  public partial class A_ProduceEquipInfo : global::ProtoBuf.IExtensible
  {
    public A_ProduceEquipInfo() {}
    
    private ProduceEquipInfo _proEquipInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"proEquipInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProduceEquipInfo proEquipInfo
    {
      get { return _proEquipInfo; }
      set { _proEquipInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_PickupProCompleteEquip")]
  public partial class RQ_PickupProCompleteEquip : global::ProtoBuf.IExtensible
  {
    public RQ_PickupProCompleteEquip() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_PickupProCompleteEquip")]
  public partial class RS_PickupProCompleteEquip : global::ProtoBuf.IExtensible
  {
    public RS_PickupProCompleteEquip() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }

    private ProduceEquipInfo _equip = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProduceEquipInfo equip
    {
      get { return _equip; }
      set { _equip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllMagicSkillInfo")]
  public partial class AllMagicSkillInfo : global::ProtoBuf.IExtensible
  {
    public AllMagicSkillInfo() {}
    
    private readonly global::System.Collections.Generic.List<MagicSkillInfo> _proMagicSkill = new global::System.Collections.Generic.List<MagicSkillInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"proMagicSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MagicSkillInfo> proMagicSkill
    {
      get { return _proMagicSkill; }
    }
  
    private readonly global::System.Collections.Generic.List<MagicSkillInfo> _completMagicSkill = new global::System.Collections.Generic.List<MagicSkillInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"completMagicSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MagicSkillInfo> completMagicSkill
    {
      get { return _completMagicSkill; }
    }
  
    private readonly global::System.Collections.Generic.List<MagicSkillInfo> _battleInUseMagicSkill = new global::System.Collections.Generic.List<MagicSkillInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"battleInUseMagicSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MagicSkillInfo> battleInUseMagicSkill
    {
      get { return _battleInUseMagicSkill; }
    }
  
    private readonly global::System.Collections.Generic.List<MagicSkillLevel> _magicSkillLevel = new global::System.Collections.Generic.List<MagicSkillLevel>();
    [global::ProtoBuf.ProtoMember(4, Name=@"magicSkillLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MagicSkillLevel> magicSkillLevel
    {
      get { return _magicSkillLevel; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MagicSkillInfo")]
  public partial class MagicSkillInfo : global::ProtoBuf.IExtensible
  {
    public MagicSkillInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _skillState;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skillState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillState
    {
      get { return _skillState; }
      set { _skillState = value; }
    }
    private long _skillTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"skillTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long skillTime
    {
      get { return _skillTime; }
      set { _skillTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MagicSkillLevel")]
  public partial class MagicSkillLevel : global::ProtoBuf.IExtensible
  {
    public MagicSkillLevel() {}
    
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _levelUpTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"levelUpTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelUpTime
    {
      get { return _levelUpTime; }
      set { _levelUpTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_ResearchMagicSkill")]
  public partial class RQ_ResearchMagicSkill : global::ProtoBuf.IExtensible
  {
    public RQ_ResearchMagicSkill() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_ResearchMagicSkill")]
  public partial class RS_ResearchMagicSkill : global::ProtoBuf.IExtensible
  {
    public RS_ResearchMagicSkill() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }

    private MagicSkillLevel _magicSkill = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"magicSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MagicSkillLevel magicSkill
    {
      get { return _magicSkill; }
      set { _magicSkill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_MakeMagicSkill")]
  public partial class RQ_MakeMagicSkill : global::ProtoBuf.IExtensible
  {
    public RQ_MakeMagicSkill() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }

    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_MakeMagicSkill")]
  public partial class RS_MakeMagicSkill : global::ProtoBuf.IExtensible
  {
    public RS_MakeMagicSkill() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private readonly global::System.Collections.Generic.List<MagicSkillInfo> _magicSkillings = new global::System.Collections.Generic.List<MagicSkillInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"magicSkillings", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MagicSkillInfo> magicSkillings
    {
      get { return _magicSkillings; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_AddBattleInMagicSkill")]
  public partial class RQ_AddBattleInMagicSkill : global::ProtoBuf.IExtensible
  {
    public RQ_AddBattleInMagicSkill() {}
    
    private int _positions;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"positions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int positions
    {
      get { return _positions; }
      set { _positions = value; }
    }
    private int _magicId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"magicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magicId
    {
      get { return _magicId; }
      set { _magicId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_AddBattleInMagicSkill")]
  public partial class RS_AddBattleInMagicSkill : global::ProtoBuf.IExtensible
  {
    public RS_AddBattleInMagicSkill() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private readonly global::System.Collections.Generic.List<MagicSkillInfo> _battleInUseMagicSkill = new global::System.Collections.Generic.List<MagicSkillInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"battleInUseMagicSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MagicSkillInfo> battleInUseMagicSkill
    {
      get { return _battleInUseMagicSkill; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JewelleryFactoryRoom")]
  public partial class JewelleryFactoryRoom : global::ProtoBuf.IExtensible
  {
    public JewelleryFactoryRoom() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Q_RoomState")]
  public partial class Q_RoomState : global::ProtoBuf.IExtensible
  {
    public Q_RoomState() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_RoomUpdateLevel")]
  public partial class RQ_RoomUpdateLevel : global::ProtoBuf.IExtensible
  {
    public RQ_RoomUpdateLevel() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_RoomUpdateLevel")]
  public partial class RS_RoomUpdateLevel : global::ProtoBuf.IExtensible
  {
    public RS_RoomUpdateLevel() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }

    private RoomInfo _roomInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<ConsumeItem> _returnItem = new global::System.Collections.Generic.List<ConsumeItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"returnItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ConsumeItem> returnItem
    {
      get { return _returnItem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_RoomMerger")]
  public partial class RQ_RoomMerger : global::ProtoBuf.IExtensible
  {
    public RQ_RoomMerger() {}
    
    private readonly global::System.Collections.Generic.List<int> _roomIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roomIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> roomIds
    {
      get { return _roomIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_RoomMerger")]
  public partial class RS_RoomMerger : global::ProtoBuf.IExtensible
  {
    public RS_RoomMerger() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _reqRoomIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"reqRoomIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> reqRoomIds
    {
      get { return _reqRoomIds; }
    }
  

    private RoomInfo _newroomInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"newroomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RoomInfo newroomInfo
    {
      get { return _newroomInfo; }
      set { _newroomInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_RoomSplit")]
  public partial class RQ_RoomSplit : global::ProtoBuf.IExtensible
  {
    public RQ_RoomSplit() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_RoomSplit")]
  public partial class RS_RoomSplit : global::ProtoBuf.IExtensible
  {
    public RS_RoomSplit() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private int _reqRoomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reqRoomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reqRoomId
    {
      get { return _reqRoomId; }
      set { _reqRoomId = value; }
    }
    private readonly global::System.Collections.Generic.List<RoomInfo> _rooms = new global::System.Collections.Generic.List<RoomInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rooms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RoomInfo> rooms
    {
      get { return _rooms; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_SaveAllRoom")]
  public partial class RQ_SaveAllRoom : global::ProtoBuf.IExtensible
  {
    public RQ_SaveAllRoom() {}
    
    private readonly global::System.Collections.Generic.List<RoomInfo> _room = new global::System.Collections.Generic.List<RoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RoomInfo> room
    {
      get { return _room; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_SaveAllRoom")]
  public partial class RS_SaveAllRoom : global::ProtoBuf.IExtensible
  {
    public RS_SaveAllRoom() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private readonly global::System.Collections.Generic.List<RoomInfo> _allRoom = new global::System.Collections.Generic.List<RoomInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"allRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RoomInfo> allRoom
    {
      get { return _allRoom; }
    }
  
    private readonly global::System.Collections.Generic.List<ResidentInfo> _allResident = new global::System.Collections.Generic.List<ResidentInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"allResident", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResidentInfo> allResident
    {
      get { return _allResident; }
    }
  
    private readonly global::System.Collections.Generic.List<ProduceRoom> _allProRoom = new global::System.Collections.Generic.List<ProduceRoom>();
    [global::ProtoBuf.ProtoMember(5, Name=@"allProRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProduceRoom> allProRoom
    {
      get { return _allProRoom; }
    }
  
    private readonly global::System.Collections.Generic.List<StoreRoom> _allStoreRoom = new global::System.Collections.Generic.List<StoreRoom>();
    [global::ProtoBuf.ProtoMember(6, Name=@"allStoreRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<StoreRoom> allStoreRoom
    {
      get { return _allStoreRoom; }
    }
  
    private readonly global::System.Collections.Generic.List<ResidentRoom> _allResidentRoom = new global::System.Collections.Generic.List<ResidentRoom>();
    [global::ProtoBuf.ProtoMember(7, Name=@"allResidentRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResidentRoom> allResidentRoom
    {
      get { return _allResidentRoom; }
    }
  

    private ProduceEquipInfo _proEquip = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"proEquip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProduceEquipInfo proEquip
    {
      get { return _proEquip; }
      set { _proEquip = value; }
    }

    private AllMagicSkillInfo _allMagicSkill = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"allMagicSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllMagicSkillInfo allMagicSkill
    {
      get { return _allMagicSkill; }
      set { _allMagicSkill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResidentInfo")]
  public partial class ResidentInfo : global::ProtoBuf.IExtensible
  {
    public ResidentInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _talentAttr = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"talentAttr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> talentAttr
    {
      get { return _talentAttr; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _talentAttrUpdateBeginTime = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"talentAttrUpdateBeginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> talentAttrUpdateBeginTime
    {
      get { return _talentAttrUpdateBeginTime; }
    }
  

    private int _battlePower = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"battlePower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battlePower
    {
      get { return _battlePower; }
      set { _battlePower = value; }
    }

    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _equips = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> equips
    {
      get { return _equips; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _attrs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"attrs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> attrs
    {
      get { return _attrs; }
    }
  

    private int _startLv = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"startLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startLv
    {
      get { return _startLv; }
      set { _startLv = value; }
    }

    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _hairAndBeard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"hairAndBeard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> hairAndBeard
    {
      get { return _hairAndBeard; }
    }
  

    private int _womanPrivileges = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"womanPrivileges", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int womanPrivileges
    {
      get { return _womanPrivileges; }
      set { _womanPrivileges = value; }
    }

    private int _womanPrivilegesTime = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"womanPrivilegesTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int womanPrivilegesTime
    {
      get { return _womanPrivilegesTime; }
      set { _womanPrivilegesTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChildAndBaby")]
  public partial class ChildAndBaby : global::ProtoBuf.IExtensible
  {
    public ChildAndBaby() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }

    private long _birthday = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"birthday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long birthday
    {
      get { return _birthday; }
      set { _birthday = value; }
    }
    private int _hairStyle;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hairStyle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hairStyle
    {
      get { return _hairStyle; }
      set { _hairStyle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_ConfirmRearKid")]
  public partial class RQ_ConfirmRearKid : global::ProtoBuf.IExtensible
  {
    public RQ_ConfirmRearKid() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_ConfirmRearKid")]
  public partial class RS_ConfirmRearKid : global::ProtoBuf.IExtensible
  {
    public RS_ConfirmRearKid() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }

    private ChildAndBaby _child = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"child", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ChildAndBaby child
    {
      get { return _child; }
      set { _child = value; }
    }

    private int _motherId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"motherId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int motherId
    {
      get { return _motherId; }
      set { _motherId = value; }
    }

    private int _fatherId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fatherId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fatherId
    {
      get { return _fatherId; }
      set { _fatherId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_ConfirmKidAdult")]
  public partial class RQ_ConfirmKidAdult : global::ProtoBuf.IExtensible
  {
    public RQ_ConfirmKidAdult() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_ConfirmKidAdult")]
  public partial class RS_ConfirmKidAdult : global::ProtoBuf.IExtensible
  {
    public RS_ConfirmKidAdult() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }

    private ResidentInfo _adult = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"adult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ResidentInfo adult
    {
      get { return _adult; }
      set { _adult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_ConfirmTrain")]
  public partial class RQ_ConfirmTrain : global::ProtoBuf.IExtensible
  {
    public RQ_ConfirmTrain() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_ConfirmTrain")]
  public partial class RS_ConfirmTrain : global::ProtoBuf.IExtensible
  {
    public RS_ConfirmTrain() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }

    private ResidentInfo _residentInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"residentInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ResidentInfo residentInfo
    {
      get { return _residentInfo; }
      set { _residentInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_DragIntoRoom")]
  public partial class RQ_DragIntoRoom : global::ProtoBuf.IExtensible
  {
    public RQ_DragIntoRoom() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_DragIntoRoom")]
  public partial class RS_DragIntoRoom : global::ProtoBuf.IExtensible
  {
    public RS_DragIntoRoom() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private readonly global::System.Collections.Generic.List<ResidentInfo> _residentInfos = new global::System.Collections.Generic.List<ResidentInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"residentInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResidentInfo> residentInfos
    {
      get { return _residentInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_ExchangeResident")]
  public partial class RQ_ExchangeResident : global::ProtoBuf.IExtensible
  {
    public RQ_ExchangeResident() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentInfo")]
  public partial class EquipmentInfo : global::ProtoBuf.IExtensible
  {
    public EquipmentInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _itemId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }

    private long _gainTime = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gainTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gainTime
    {
      get { return _gainTime; }
      set { _gainTime = value; }
    }

    private int _equiptor = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"equiptor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equiptor
    {
      get { return _equiptor; }
      set { _equiptor = value; }
    }

    private int _isRead = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isRead", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isRead
    {
      get { return _isRead; }
      set { _isRead = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropInfo")]
  public partial class PropInfo : global::ProtoBuf.IExtensible
  {
    public PropInfo() {}
    
    private int _propId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"propId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int propId
    {
      get { return _propId; }
      set { _propId = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Box")]
  public partial class Box : global::ProtoBuf.IExtensible
  {
    public Box() {}
    
    private readonly global::System.Collections.Generic.List<EquipmentInfo> _equips = new global::System.Collections.Generic.List<EquipmentInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipmentInfo> equips
    {
      get { return _equips; }
    }
  
    private readonly global::System.Collections.Generic.List<PropInfo> _bxAndProps = new global::System.Collections.Generic.List<PropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bxAndProps", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropInfo> bxAndProps
    {
      get { return _bxAndProps; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShowItem")]
  public partial class ShowItem : global::ProtoBuf.IExtensible
  {
    public ShowItem() {}
    
    private readonly global::System.Collections.Generic.List<EquipmentInfo> _equips = new global::System.Collections.Generic.List<EquipmentInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipmentInfo> equips
    {
      get { return _equips; }
    }
  
    private readonly global::System.Collections.Generic.List<PropInfo> _props = new global::System.Collections.Generic.List<PropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"props", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropInfo> props
    {
      get { return _props; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"A_QiPao")]
  public partial class A_QiPao : global::ProtoBuf.IExtensible
  {
    public A_QiPao() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _jumingId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"jumingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jumingId
    {
      get { return _jumingId; }
      set { _jumingId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"A_HappinessState")]
  public partial class A_HappinessState : global::ProtoBuf.IExtensible
  {
    public A_HappinessState() {}
    

    private int _happinessNum = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"happinessNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int happinessNum
    {
      get { return _happinessNum; }
      set { _happinessNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RQ_Reconnect")]
  public partial class RQ_Reconnect : global::ProtoBuf.IExtensible
  {
    public RQ_Reconnect() {}
    
    private string _sessionToken;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionToken
    {
      get { return _sessionToken; }
      set { _sessionToken = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RS_Reconnect")]
  public partial class RS_Reconnect : global::ProtoBuf.IExtensible
  {
    public RS_Reconnect() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"A_ErrorMessage")]
  public partial class A_ErrorMessage : global::ProtoBuf.IExtensible
  {
    public A_ErrorMessage() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"A_SessionToken")]
  public partial class A_SessionToken : global::ProtoBuf.IExtensible
  {
    public A_SessionToken() {}
    
    private string _sessionToken;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionToken
    {
      get { return _sessionToken; }
      set { _sessionToken = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}